package model;
// Generated Oct 26, 2014 8:09:06 PM by Hibernate Tools 3.6.0



/**
 * TbHari generated by hbm2java
 */
public class Hari  implements java.io.Serializable {


    private String idHari;
    private String hari;
    
    //untuk pengesetan combobox
    public Hari() {
    }
    
    //untuk helper combobox
    public Hari(String idHari, String hari) {
       this.idHari = idHari;
       this.hari = hari;
    }
   
    public String getIdHari() {
        return this.idHari;
    }
    
    public void setIdHari(String idHari) {
        this.idHari = idHari;
    }
    public String getHari() {
        return this.hari;
    }
    
    public void setHari(String hari) {
        this.hari = hari;
    }

    @Override
    public String toString() {
        return hari; //To change body of generated methods, choose Tools | Templates.
    }




}


