/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import javax.swing.JComboBox;
import controller.ControllerMengisiPertemuan;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author muhriansyah
 */
public class FrameIsiPresensiKelas extends javax.swing.JDialog {

    ControllerMengisiPertemuan cip = null;
    int idPbm;
    
    /**
     * Creates new form FramePresensiKelas
     *
     * @param parent
     * @param modal
     */
    public FrameIsiPresensiKelas(java.awt.Frame parent, boolean modal, int idKelas, int pertemuan, int idMapel) {
        super(parent, modal);
        initComponents();
        cip = new ControllerMengisiPertemuan(this, idKelas, pertemuan);
        cip.melihatIsiPresensi(idMapel);
        this.idPbm = FramePresensiKelas.idPbm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusHadirGuruGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        presensiTable = new javax.swing.JTable();
        simpanButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pertemuanText = new javax.swing.JTextField();
        materiComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        beritaAcaraText = new javax.swing.JTextArea();
        tanggalText = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        hadirRadioButton = new javax.swing.JRadioButton();
        tidakHadirRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Isi Daftar Hadir");

        presensiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123040226", "Riansyah", null},
                {"123040227", "Nanda", null},
                {"123040229", "Shelly", null},
                {"123040187", "Yepi Dedehidayat", null},
                {"123040141", "Fauzan", null},
                {"123040212", "Hilal ", null}
            },
            new String [] {
                "NRP", "Nama", "Status Kehadiran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(presensiTable);

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Pertemuan Ke");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Bab");

        jLabel5.setText("Berita Acara");

        pertemuanText.setEditable(false);
        pertemuanText.setText("1");

        materiComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        materiComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                materiComboBoxMouseEntered(evt);
            }
        });
        materiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiComboBoxActionPerformed(evt);
            }
        });

        beritaAcaraText.setColumns(20);
        beritaAcaraText.setRows(5);
        jScrollPane2.setViewportView(beritaAcaraText);

        jLabel1.setText("Status kehadiran guru");

        statusHadirGuruGroup.add(hadirRadioButton);
        hadirRadioButton.setSelected(true);
        hadirRadioButton.setText("Hadir");
        hadirRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hadirRadioButtonActionPerformed(evt);
            }
        });

        statusHadirGuruGroup.add(tidakHadirRadioButton);
        tidakHadirRadioButton.setText("Tidak Hadir");
        tidakHadirRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidakHadirRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(materiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pertemuanText, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(simpanButton)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(hadirRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(tidakHadirRadioButton)))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pertemuanText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tanggalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(hadirRadioButton)
                    .addComponent(tidakHadirRadioButton))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(simpanButton)
                .addGap(15, 15, 15))
        );

        pertemuanText.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        //opsi method ada 2 yakni ubah atau simpan
        cip.menyimpanPresensi(idPbm);
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void materiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiComboBoxActionPerformed
        // TODO add your handling code here:
//        MataPelajaran materi = (MataPelajaran) this.getMateriComboBox().getSelectedItem();
//        System.out.println(materi.getIdMateri());
    }//GEN-LAST:event_materiComboBoxActionPerformed

    private void materiComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materiComboBoxMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_materiComboBoxMouseEntered
    private String statusKehadiranGuru = "hadir";

    public String getStatusKehadiranGuru() {
        return statusKehadiranGuru;
    }
    
    private void hadirRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hadirRadioButtonActionPerformed
        // TODO add your handling code here:
        statusKehadiranGuru = "hadir";
    }//GEN-LAST:event_hadirRadioButtonActionPerformed

    private void tidakHadirRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidakHadirRadioButtonActionPerformed
        // TODO add your handling code here:
        statusKehadiranGuru = "tidak";
    }//GEN-LAST:event_tidakHadirRadioButtonActionPerformed

    public JTable getPresensiTable() {
        return presensiTable;
    }


    public JComboBox getMateriComboBox() {
        return materiComboBox;
    }


    public JTextArea getBeritaAcaraText() {
        return beritaAcaraText;
    }
  
    public JTextField getPertemuanText() {
        return pertemuanText;
    }

    public JDateChooser getTanggalText() {
        return tanggalText;
    }


    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(FrameIsiPresensiKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(FrameIsiPresensiKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(FrameIsiPresensiKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(FrameIsiPresensiKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FrameIsiPresensiKelas dialog = new FrameIsiPresensiKelas(new javax.swing.JFrame(), true,11,6,1);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea beritaAcaraText;
    private javax.swing.JRadioButton hadirRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox materiComboBox;
    private javax.swing.JTextField pertemuanText;
    private javax.swing.JTable presensiTable;
    private javax.swing.JButton simpanButton;
    private javax.swing.ButtonGroup statusHadirGuruGroup;
    private com.toedter.calendar.JDateChooser tanggalText;
    private javax.swing.JRadioButton tidakHadirRadioButton;
    // End of variables declaration//GEN-END:variables
}
