/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.ControllerMelihatBelajarMengajar;
import javax.swing.JTable;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import model.Hari;
/**
 *
 * @author muhriansyah
 */
public class FrameBelajarMengajar extends javax.swing.JFrame {
    private ControllerMelihatBelajarMengajar cbm;
    /**
     * Creates new form prototipe
     */
    public FrameBelajarMengajar() {
        initComponents();
        int idhari = 1;//id 1 itu hari senin
        cbm = new ControllerMelihatBelajarMengajar(this,idhari);
        cbm.setTabelBelajarMengajar();
        cbm.setComboBoxHari();
    }

    
    public JComboBox getHariComboBox() {
        return hariComboBox;
    }

   
    public JTable getBelajarMengajarTable() {
        return belajarMengajarTable;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The clontent of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        keluarButton = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        panelBeranda = new javax.swing.JPanel();
        berandaLabel = new javax.swing.JLabel();
        panelKegiatanBelajarMengajar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        belajarMengajarTable = new javax.swing.JTable();
        hariComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SI BELJAR");

        jLabel2.setText("Halo Admin !");

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        tab.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        berandaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        berandaLabel.setText("Selamat anda masuk sebagai admin !");

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(berandaLabel)
                .addContainerGap(454, Short.MAX_VALUE))
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(berandaLabel)
                .addContainerGap(448, Short.MAX_VALUE))
        );

        tab.addTab("Beranda", panelBeranda);

        belajarMengajarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "I - 1", "14.00-15.00", "Matematika", "Rinaldi Munir"},
                {"2", "I - 2", "10.00-12.00", "Biologi", "Onno w"},
                {"3", "III - 3", "07.00-10.00", "Matematika", "Rinaldi Munir"},
                {"4", "II - 2", "09.00-10.00", "Kimia", "Reyhan"},
                {"5", "I - 4", "09.00-13.00", "Kimia", "Reyhan"},
                {"6", "II - 4", "09.00-10.00", "Matematika", "Rinaldi Munir"}
            },
            new String [] {
                "Id", "Kelas", "Jam Pelajaran", "Mata Pelajaran", "Guru"
            }
        ));
        belajarMengajarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                belajarMengajarTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(belajarMengajarTable);

        hariComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hariComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("*Pilih salah satu jadwal belajar mengajar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("*Pilih hari");

        javax.swing.GroupLayout panelKegiatanBelajarMengajarLayout = new javax.swing.GroupLayout(panelKegiatanBelajarMengajar);
        panelKegiatanBelajarMengajar.setLayout(panelKegiatanBelajarMengajarLayout);
        panelKegiatanBelajarMengajarLayout.setHorizontalGroup(
            panelKegiatanBelajarMengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKegiatanBelajarMengajarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelKegiatanBelajarMengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(panelKegiatanBelajarMengajarLayout.createSequentialGroup()
                        .addGroup(panelKegiatanBelajarMengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(panelKegiatanBelajarMengajarLayout.createSequentialGroup()
                                .addComponent(hariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelKegiatanBelajarMengajarLayout.setVerticalGroup(
            panelKegiatanBelajarMengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKegiatanBelajarMengajarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelKegiatanBelajarMengajarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hariComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tab.addTab("Presensi", panelKegiatanBelajarMengajar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(keluarButton)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tab)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(keluarButton))
                .addGap(18, 18, 18)
                .addComponent(tab)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FrameLogin().setVisible(true);
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void hariComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hariComboBoxActionPerformed
        // TODO add your handling code here:
        Hari hari ;
        hari = (Hari) hariComboBox.getSelectedItem();                
        int idHari = Integer.parseInt(hari.getIdHari());
        cbm = new ControllerMelihatBelajarMengajar(this, idHari);
        cbm.setTabelBelajarMengajar();
        
    }//GEN-LAST:event_hariComboBoxActionPerformed
    private void belajarMengajarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_belajarMengajarTableMouseClicked
        // TODO add your handling code here:
        int rowBM = belajarMengajarTable.getSelectedRow();
        String SbelajarMengajar = belajarMengajarTable.getValueAt(rowBM, 0).toString();
        int idPbm = Integer.parseInt(SbelajarMengajar);
        //krn report ga bisa tampil jadi bukan dialog tapi frame biasa
//        new FramePresensiKelas(new JFrame(),true,idPbm).setVisible(true);
        new FramePresensiKelas(idPbm).setVisible(true);
    }//GEN-LAST:event_belajarMengajarTableMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrameBelajarMengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrameBelajarMengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrameBelajarMengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrameBelajarMengajar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrameBelajarMengajar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable belajarMengajarTable;
    private javax.swing.JLabel berandaLabel;
    private javax.swing.JComboBox hariComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluarButton;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelKegiatanBelajarMengajar;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
